### ISSUE TITLE
Skymap alignment on full screen preview

### ISSUE THREAD

**Issue by RiccardoBuscicchio** [scooper93/Chirp#1]
The full screen preview of skymaps moves up and down in vertical orientation, both for tap and press&hold.
Specs:
Android 9 PKQ1.180904.001
6.3" display, 1080x2340 resolution, 19.5:9 aspect

[Screen recording](https://photos.app.goo.gl/QNVERLwFAdno8bcr7)

**Comment by scooper93** [comment]
I think this has been fixed -at least on my test devices.
