### ISSUE TITLE
Text and typos

### ISSUE THREAD

**Issue by SeanDS** [scooper93/Chirp#12]
In the introduction page "Listening to the Cosmos", Virgo seems like an "also ran" type of mention. I would flesh Virgo's description out a bit, to say e.g. "The two LIGO detectors in Hanford and Livingston, and the Virgo detector in Italy, have a proven track record..."

Typos:
Description for False Alarm Rate: "ammount" should be "amount".
"Kagra" description in "About": should be "KAGRA".

**Comment by scooper93** [comment]
Fixed in an upcoming release.
