### ISSUE TITLE
Notifications?

### ISSUE THREAD

**Issue by SeanDS** [scooper93/Chirp#13]
It would be great to be able to get a notification from the app when there is a new event. Is this planned?

**Comment by scooper93** [comment]
Currently implmenting this on a development branch, I've got remote messaging sorted now, so I just need to tidy up some interface stuff and sort out user preferences.

**Comment by axj336** [comment]
The server-side code is now running on the dev server for each alert.

**Comment by scooper93** [comment]
This is now working on iOS and Android in our development version.
