### ISSUE TITLE
Proposed change to mass gap text.

### ISSUE THREAD

**Issue by axj336** [scooper93/Chirp#19]
The mass gap text currently reads: "Source between 3 & 5 solar masses"

We propose changing this to: "Most Likely Origin: Binary with at least one component between 3 & 5 solar masses (mass gap)"

to make the distinction that it is one component between 3&5 solar masses and not the combined mass.

**Comment by scooper93** [comment]
I do not like this wording change. Its too long and not snappy enough. 

Alternatives: 'At least one object between 3-5 solar masses (MassGap)'

'One or more objects between 3-5 solar masses'

'At least one object between 3-5 solar masses'

**Comment by scooper93** [comment]
This has been implemented on the dev branch and will move to master.
