### ISSUE TITLE
Native: All alerts key not closing on back

### ISSUE THREAD

**Issue by philj56** [scooper93/Chirp#20]
The "Likely Type" key popup on the all alerts page doesn't close when pressing the back button on Android.

**Comment by scooper93** [comment]
What phone @philj56 ? I've tried it (admittedly on a development build) and cannot reproduce.

**Comment by philj56** [comment]
Pixel 2 on Android 10

**Comment by scooper93** [comment]
Just leaving a note to myself that this doesn't show up on the development build as the settings icon is in the way.

**Comment by scooper93** [comment]
This has been fixed in the latest commit
