### ISSUE TITLE
Native: Modals

### ISSUE THREAD

**Issue by scooper93** [scooper93/Chirp#3]
Some suggestions for modals.

- Make the hitbox for opening them bigger? Maybe to include the field name?
- ~~Less jarring opening animation, suggest something other than opening from the side~~
- ~~Flashing modal background on closing of modal.~~

- Modal text is not consistent
- False alarm rate is confusing
- ~~Alert circulars do not have a modal~~

**Comment by philj56** [comment]
In addition:
  - Back button should close modals on android
  - Role modal is missing some text: [Screenshot](https://i.ibb.co/tQwZ76y/Screenshot-20191001-104404.png)

**Comment by scooper93** [comment]
Back button now closes modals and animation is less jarring
Event circulars now has a modal

Role appears to be working on tablet, must be a phone only bug

**Comment by scooper93** [comment]
This has now been fixed.
